site_name: Time Based Design â€“ theory
copyright: HG 2025
site_author: Bart Barnard and Hille Engelsma
site_description: 'Theoretical module of Time Based Design'
use_directory_urls: false

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'orange'
  icon:
    logo: 'material/library'
  language: 'en'
  include_sidebar: false
extra_css:
  - css/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - markdown.extensions.codehilite:
      guess_lang: False
      linenums: True
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 3
  - markdown.extensions.def_list
  - markdown.extensions.admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 

extra_javascript:
  - js/imgs.js

nav:
  - Introduction: index.md
  - Assessment and learning outcomes: assessment.md
  - Presentations: presentations.md
  - 1. World and Reality:
    - Nature is what we see: week1/nature.md
    - Introduction: week1/week1.md
    - Exercises: week1/exercises.md
  - 2. Time and Space:
    - La Notte Bella: week2/la-notte-bella.md
    - Introduction: week2/week2.md
    - Exercises: week2/exercises.md
  - 3. Fact and Fiction:
    - Introduction: week3/week3.md
    - Exercises: week3/exercises.md
  - 4. Us and Them:
    - Introduction: week4/week4.md
    - Exercises: week4/exercises.md
  - 5. Presence and Absence:
    - Introduction: week5/week5.md
    - Exercises: week5/exercises.md
  - 6. Word and Object:
    - Introduction: week6/week6.md
    - Exercises: week6/exercises.md
#  - 7. Resonance and Alienation: week7.md
#  - 8. Synthesis and Evaluation: week8.md
  - Literature: literature.md